name: libraryapp

# ワークフローをいつ実行するかを制御
on:
  # プッシュリクエストイベントでメインブランチに対してワークフローをトリガーする
  push:
    branches: [ master ]
    
  #[アクション]タブからこのワークフローを手動で実行できる
  workflow_dispatch:

jobs:
  build:
    # ジョブが実行されるランナーのタイプ実行環境
    runs-on: ubuntu-latest

    # ステップは、ジョブの一部として実行される一連のタスクを表す
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: '11'

      - name: Maven purge
        #run: ./mvnw dependency:purge-local-repository -DreResolve=false -f src/main/webapp/META-INF/maven/library/library/pom.xml
        run: mvn dependency:purge-local-repository -DreResolve=false -f pom.xml

      - name: Build and Test with Maven
        #run: ./mvnw clean package -f src/main/webapp/META-INF/maven/library/library/pom.xml
        run: mvn clean package -f pom.xml

       # DockerHub ログイン
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKRHUB_USERNAME }}
          password: ${{ secrets.DOCKRHUB_TOKEN }}

      # BuildKitの有効化
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       
      # コンテナビルド＆格納
      - name: Build and push 
        run: |
          docker build -t yuuka65/libraryapp:latest . 
          docker push yuuka65/libraryapp:latest


